#imperative
#kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123



apiVersion: v1
kind: Pod
metadata:
   name: simple-webapp-color
   labels:
      name: simple-webapp-color 
spec:
   containers:
      - name: simple-webapp-color
        image: simple-webapp-color
        ports: 
           - containerPort: 8080
        envFrom:
           - secretRef:
               name: app-secret 

#secret-data.yaml

#apiversion: v1
#kind: Secret
#metadata: 
#   name: app-secret 
#data:
#   DB_Host: mysql
#   DB_User: root
#   DB_Password: Paswrd

### Secrtet in Posds

#Env
envFrom:
   - secretRef:
        name:app-config 

#Single Env

env: 
  - name: DB_Password 
    valueFrom: 
       secretKeyRef: 
          name: app_secret 
          key: DB_Password 

#Volume 

volumes: 
  - name: app-secret-volumes
    secret: 
       secretName: app_secret 

