apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - mountPath: /var/www/html
      name: doc-root
  volumes:
  - name: doc-root
    persistentVolumeClaim:
       claimName: local-pvc