apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: cluster-administrator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "create", "delete"]

#kubectl get clusterroles --no-headers | wc -l
#kubectl get clusterroles --no-headers -o json | jq '.items | length'