apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
subjects:
- kind: User 
  name: dev-user
  apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role 
  name: developer 
  apiGruop: rbac.authorization.k8s.io/v1


#kubectl get roles 
#kubectl get rolebindings
#kubectl describe role developer
#kubectl describe rolebinding devuser-developer-binding


# Check Access #

#kubectl auth can-i create deployments
#kubectl auth can-i delete nodes
#kubectl auth can-i create deployments --as dev-user 
#kubectl auth can-i create pods --as dev-user --namespace test 


#kubectl describe role kube-proxy -n kube-system