apiVersion: v1 
kind: ResourceQuota
metadata:
   name: compute-quota
   namespace: dev
spec:
   hard:
      pods: "10"
      requests.cpu: "4"
      requests.memory: 5Gi
      limits.cpu: "10"
      limits.memory: 10Gi

#kubectl create -f namespace-resource-quota.yml
#kubectl get pods --all-namespaces | grep blue