#kubectl get pods
#kubectl get pods --namespace=kub-system
apiVersion: v1 
kind: Pod 
metadata:
   name: myapp-pod 
   namespace: dev 
   labels:
      app: myapp
      type: front-end
spec: 
   containers:
      - name: nginx-container
        image: nginx

   
#kubectl create -f pod-definition.yml --namespace=dev 
