apiVersion: v1 
kind: service 
metadata:
   name: nginx-ingress
spec: 
   type: NodePort
   ports:
   - ports: 80
     targetPort: 80
     protocol: TCP
     name: http
   - ports: 443
     targetPort: 443
     protocol: TCP 
     name: https 
   selector:
      name: nginx-ingress 

  ## and then create Service Account 
   